<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>


<ItemGroup>
  <ProjectReference Include="..\..\src\Viset.Core\Viset.Core.fsproj" />
  <ProjectReference Include="..\..\src\Viset.Browser\Viset.Browser.fsproj" />
  <ProjectReference Include="..\..\src\Viset.Browser.Management\Viset.Browser.Management.fsproj" />
  <ProjectReference Include="..\..\src\Viset.WebP\Viset.WebP.fsproj" />
</ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" />
    <PackageReference Include="StbImageSharp" />
  </ItemGroup>

</Project>
