version = 1
publisher = "Google Chrome for Testing"
browser_version = "150.0.7871.124"
revision = "r1639810"

[platforms.linux-x64]
url = "https://storage.googleapis.com/chrome-for-testing-public/150.0.7871.124/linux64/chrome-linux64.zip"
sha256 = "ccb11556d5946fcf15f09d175c34d8e4b4293a8ef2eb7c4efc28cb60ac4d12fd"
executable = "chrome-linux64/chrome"

[platforms.win-x64]
url = "https://storage.googleapis.com/chrome-for-testing-public/150.0.7871.124/win64/chrome-win64.zip"
sha256 = "65fff74a602e0487fac43a148229b56d859070ac1b0e3d002d21d8edae3cfafe"
executable = "chrome-win64/chrome.exe"

[platforms.osx-arm64]
url = "https://storage.googleapis.com/chrome-for-testing-public/150.0.7871.124/mac-arm64/chrome-mac-arm64.zip"
sha256 = "36c8b5fe04c08a418a172206bb392600ec1550941bde6af2d4353df21db87a47"
executable = "chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing"
