<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="CaptureRequest.fs" />
    <Compile Include="CaptureScript.Primitives.fs" />
    <Compile Include="CaptureHeader.fs" />
    <Compile Include="TomlValueParser.fs" />
    <Compile Include="CaptureDeviceParser.fs" />
    <Compile Include="CaptureOutputTemplate.fs" />
    <Compile Include="WebPOptionsParser.fs" />
    <Compile Include="CapturePlanner.fs" />
    <Compile Include="CaptureScript.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Tomlyn" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Viset.Core\Viset.Core.fsproj" />
    <ProjectReference Include="..\Viset.Serialization\Viset.Serialization.csproj" />
  </ItemGroup>
</Project>
