<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="WebPInteropTypes.fs" />
    <Compile Include="WebPInterop.fs" />
    <Compile Include="WebPNativeTypes.fs" />
    <Compile Include="WebPNativeDimensions.fs" />
    <Compile Include="WebPNativeLibraries.fs" />
    <Compile Include="WebPInteropLayouts.fs" />
    <Compile Include="WebPNativeConfig.fs" />
    <Compile Include="WebPNativeData.fs" />
    <Compile Include="LibWebPFullNative.fs" />
    <Compile Include="LibWebPAnimNative.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Imazen.WebP.NativeRuntime.All" />
  </ItemGroup>
</Project>
