<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="CdpTypes.fs" />
    <Compile Include="CdpTransport.fs" />
    <Compile Include="CdpClient.fs" />
    <Compile Include="BrowserSessionTypes.fs" />
    <Compile Include="BrowserProcess.fs" />
    <Compile Include="BrowserSession.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Viset.Core\Viset.Core.fsproj" />
    <ProjectReference Include="..\Viset.Serialization\Viset.Serialization.csproj" />
  </ItemGroup>
</Project>
